Update util.js
The change allows for having routes files within subdirectories and eliminating error:
TypeError: undefined is not a function
due to "callback" being undefined